/*
 * Copyright 2026 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package model

import (
	"github.com/cloudwego/eino/callbacks"
	"github.com/cloudwego/eino/schema"
)

// AgenticConfig is the config for the agentic model.
// AgenticConfig 是 agentic model 的配置。
type AgenticConfig struct {
	// Model is the model name.
	// Model 是模型名称。
	Model string
	// MaxTokens is the max number of output tokens, if reached the max tokens, the model will stop generating.
	// MaxTokens 是输出 token 的最大数量；达到最大 token 数时，模型将停止生成。
	MaxTokens int
	// Temperature is the temperature, which controls the randomness of the agentic model.
	// Temperature 是温度，用于控制 agentic model 的随机性。
	Temperature float32
	// TopP is the top p, which controls the diversity of the agentic model.
	// TopP 是 top p，用于控制 agentic model 的多样性。
	TopP float32
}

// AgenticCallbackInput is the input for the agentic model callback.
// AgenticCallbackInput 是 agentic model 回调的输入。
type AgenticCallbackInput struct {
	// Messages is the agentic messages to be sent to the agentic model.
	// Messages 是要发送给 agentic model 的 agentic messages。
	Messages []*schema.AgenticMessage
	// Tools is the tools to be used in the agentic model.
	// Tools 是 agentic model 中要使用的工具。
	Tools []*schema.ToolInfo
	// Config is the config for the agentic model.
	// Config 是 agentic model 的配置。
	Config *AgenticConfig
	// Extra is the extra information for the callback.
	// Extra 是回调的额外信息。
	Extra map[string]any
}

// AgenticCallbackOutput is the output for the agentic model callback.
// AgenticCallbackOutput 是 agentic model 回调的输出。
type AgenticCallbackOutput struct {
	// Message is the agentic message generated by the agentic model.
	// Message 是 agentic model 生成的 agentic message。
	Message *schema.AgenticMessage
	// Config is the config for the agentic model.
	// Config 是 agentic model 的配置。
	Config *AgenticConfig
	// TokenUsage is the token usage of this request.
	// TokenUsage 是本次请求的 token 使用情况。
	TokenUsage *TokenUsage
	// Extra is the extra information for the callback.
	// Extra 是回调的额外信息。
	Extra map[string]any
}

// ConvAgenticCallbackInput converts the callback input to the agentic model callback input.
// ConvAgenticCallbackInput 将回调输入转换为 agentic model 回调输入。
func ConvAgenticCallbackInput(src callbacks.CallbackInput) *AgenticCallbackInput {
	switch t := src.(type) {
	case *AgenticCallbackInput:
		// when callback is triggered within component implementation,
		// the input is usually already a typed *model.AgenticCallbackInput
		//
		// 当回调在组件实现内部触发时，
		// 输入通常已经是类型化的 *model.AgenticCallbackInput
		return t
	case []*schema.AgenticMessage:
		// when callback is injected by graph node, not the component implementation itself,
		// the input is the input of Agentic Model interface, which is []*schema.AgenticMessage
		//
		// 当回调由图节点注入，而不是组件实现本身注入时，
		// 输入是 Agentic Model 接口的输入，即 []*schema.AgenticMessage
		return &AgenticCallbackInput{
			Messages: t,
		}
	default:
		return nil
	}
}

// ConvAgenticCallbackOutput converts the callback output to the agentic model callback output.
// ConvAgenticCallbackOutput 将回调输出转换为 agentic model 回调输出。
func ConvAgenticCallbackOutput(src callbacks.CallbackOutput) *AgenticCallbackOutput {
	switch t := src.(type) {
	case *AgenticCallbackOutput:
		// when callback is triggered within component implementation,
		// the output is usually already a typed *model.AgenticCallbackOutput
		//
		// 当回调在组件实现内部触发时，
		// 输出通常已经是类型化的 *model.AgenticCallbackOutput
		return t
	case *schema.AgenticMessage:
		// when callback is injected by graph node, not the component implementation itself,
		// the output is the output of Agentic Model interface, which is *schema.AgenticMessage
		//
		// 当回调由图节点注入，而不是组件实现本身注入时，
		// 输出是 Agentic Model 接口的输出，即 *schema.AgenticMessage
		return &AgenticCallbackOutput{
			Message: t,
		}
	default:
		return nil
	}
}
